### ISSUE TITLE
How to rename default passport cookie name 'laravel_token'?

### ISSUE THREAD

**Issue by MovingGifts** [huwcarwyn/react-laravel-boilerplate#11]
First off, thank you for putting this together, it's a very nice package!

I was looking for a way to overwrite the default passport cookie `laravel_token` name to something else like `custom_token` for example. I only found [this resource](https://github.com/laravel/passport/issues/443#issuecomment-317383843), but when I try something like:

`Passport::cookie('custom_token');` as suggested in the example, it returns the new cookie name in the response to the browser, but it does not Authenticate or work for the next request.

I placed that snippet in the login area before the response, but maybe it's not the right place for it to work.

Any idea how to have the custom token name work with this package and authenticate requests successfully?

Note: The default `laravel_token` cookie name authenticates perfectly, so only when renamed it breaks authentication.

**Comment by huwcarwyn** [comment]
Hey, thank you very much for the kind words about the boilerplate!

I think it might be an issue with where you are placing the custom naming cookie code, it seems that by placing it in the login area, passport will only change the cookie name on that particular route. 

Could you try placing `Passport::cookie('custom_token');` in your `AppServiceProvider` (specifically the register method) and tell me if it works for you?

**Comment by MovingGifts** [comment]
That worked right away! Thank you so much again and keep up the great work!
