### ISSUE TITLE
After Login.. in first page of your application when i refresh the page. automatic logout 

### ISSUE THREAD

**Issue by kcompany420** [huwcarwyn/react-laravel-boilerplate#13]
when I am login then go to page URL /users/me.
in the first page of your boilerplate page when I refresh the page then automatic logout
and if we logout manually then error are occur in console.     error: "Unauthenticated."
GET http://127.0.0.1:8000/api/logout 401 (Unauthorized)
Uncaught (in promise) Error: Request failed with status code 401

2- can't update user profile and give same error
Uncaught (in promise) Error: Request failed with status code 401

3- and not return laravel_token in response in this line
const response = await axios.post('/api/login', loginDetails)

**Comment by huwcarwyn** [comment]
Interesting - I will look into this in a second

**Comment by huwcarwyn** [comment]
This should be fixed if you pull the latest version of master

**Comment by MouadBH** [comment]
still face this issue.
