### ISSUE TITLE
how to Give default value input Field component

### ISSUE THREAD

**Issue by kcompany420** [huwcarwyn/react-laravel-boilerplate#14]
i am giving an defaultValue attribute in your <Field > component. but not take default value
how to give default value in this component ????????

**Comment by huwcarwyn** [comment]
you can look at the [redux form docs](https://redux-form.com/8.1.0/examples/initializefromstate/) for more info on how to do that, in short: pass an object called `initialValues` to your form component, where each entry in the object is the field name along with its initial value.

**Comment by kcompany420** [comment]
i am not using reducers.
how to set initial default value in redux form Field without reducers

**Comment by huwcarwyn** [comment]
If your value is in props, but is not in an `initialValues` prop being passed to your component, the field won't pick the initial value up.

Pass your inital value prop to your child component, and the field should see it.

For example: you have a field called `firstName`

If you pass this object into the component that has your field, your field should initialise properly:

`initialValues: { firstName: 'Carwyn Stephen' }`
