### ISSUE TITLE
regeneratorRuntime is not defined error on fresh install 

### ISSUE THREAD

**Issue by jonasva** [huwcarwyn/react-laravel-boilerplate#15]
Hi, 

I setup your project locally, ran composer install, migrations, npm install and npm run production. However, when I try to load the homepage I get this error:
`Uncaught ReferenceError: regeneratorRuntime is not defined`

![screen shot 2019-03-07 at 16 03 14](https://user-images.githubusercontent.com/8156732/53941232-8a6a5b00-40f2-11e9-93cf-007e1f45ad6b.png)

Did I forgot to install something? 

Some more info:

Branch: Master

Node version: v10.15.2
NPM version: 6.9.0 

Browser: Chrome 72
OS: OSX 10.14.3

**Comment by huwcarwyn** [comment]
Hmm interesting - I'm at work right now but I'll have a look once I'm home. I don't recall me getting that error though but I'll try to reproduce it

**Comment by huwcarwyn** [comment]
OK I found the issue - the Babel polyfill wasn't being included properly (I had done this on a project I'm working on based off of this boilerplate, but not on the boilerplate itself, oops!)

I've also added the ability to skip scoping CSS via scss-modules by naming a file `.verbatim.scss`
