### ISSUE TITLE
css-loader seems not working

### ISSUE THREAD

**Issue by hamzadev7** [huwcarwyn/react-laravel-boilerplate#18]
I have built this repo by following the steps in readme file but I couldn't find generated css file.
I thought it should be in public/css folder but there were no folder named css and even app.css file.
Need some help.

**Comment by huwcarwyn** [comment]
Ah OK - I left a step out of the installation instructions that might be useful for you - can you try running `npm run dev` and tell me if you get a generated css file?

**Comment by huwcarwyn** [comment]
I'm closing this issue as I was able to successfully create an extracted CSS file by running `npm run prod` on a fresh copy of this repository.
