### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jsouzaSO** [huwcarwyn/react-laravel-boilerplate#2]
how to make it work, after installing and running the "npm run prod" command on the browser I get a blank page

**Comment by huwcarwyn** [comment]
Can you open your JS console and tell me if you're getting any errors?

**Comment by huwcarwyn** [comment]
OK I found the issue, I changed the entry for the react app from App.jsx to Main.jsx and forgot to update it in the production webpack config, I've fixed this now.
