### ISSUE TITLE
How do you setup the postman token with this boilerplate?

### ISSUE THREAD

**Issue by rovillesarate** [huwcarwyn/react-laravel-boilerplate#23]
Hi! I have been trying to setup postman with this boilerplate. How do you connect this to Postman? tried using oauth and assigning cookies but can't seem to make it work.

**Comment by huwcarwyn** [comment]
All requests to the API need the headers `X-CSRF-TOKEN` and `X-Requested-With:XMLHttpRequest`

You also need to have the laravel_token cookie set.

I personally use the insomnia HTTP client - have a saved route for the api login which fetches a cookie for me, and I have those two headers above set, and that's it!

**Comment by rovillesarate** [comment]
Thank you, Got it working. =)
