### ISSUE TITLE
npm run dev not compiling app.scss

### ISSUE THREAD

**Issue by rovillesarate** [huwcarwyn/react-laravel-boilerplate#25]
Hi! Huwcarwyn. Thank you for this wonderful boilerplate. I would just like to ask help regarding running npm run dev. It seems that its not compiling the app.scss so in the public folder no css are being loaded. Am I missing something from the weback.common.js

Do i need to setup any configs to fix this. Thank you in advance.

**Comment by huwcarwyn** [comment]
I'll have a look at this for you

**Comment by huwcarwyn** [comment]
Are the styles not loading when you visit the page or are you just not seeing a .css file? When you run `npm run dev` the styles are actually loaded in via javacript, only when you run `npm run production` is a separate minified CSS file generated.

**Comment by rovillesarate** [comment]
the styles load but the app.css does not load. that explains it. now. so i should use the npm run production instead

**Comment by huwcarwyn** [comment]
Yes - for development I would run `npm run hot` as that allows you to automatically see changes that are made without a full refresh.

**Comment by rovillesarate** [comment]
Im getting problems when running npm run production. It already compiles the app.css but im getting errors on the app.js and vendor~app.js

**Comment by huwcarwyn** [comment]
Can you post those errors?

**Comment by rovillesarate** [comment]
I found the problem. I only uploaded the app.js and vendor~app.js on my staging host. but upon testing on the local server. it seems that when i use the npm run production. its also creating additional js files that are being loaded. which is weird as i thought it only needs the app.js

its creating additional js files with numbers.
0.js, 6.js, 9.js
