### ISSUE TITLE
React Boilerplate?

### ISSUE THREAD

**Issue by rovillesarate** [huwcarwyn/react-laravel-boilerplate#28]
Hi huwcarwyn. Just wondering if your using a specific react boilerplate or a custom one for this project. Trying to understand more how the react directories in this project works.

**Comment by huwcarwyn** [comment]
I made all this myself - post a couple questions and I'll do my best to answer :)

**Comment by rovillesarate** [comment]
Im trying to understand the store directory. The action-creators, reducers, and selectors. The use of entities within the reducers directory. Lets say if i were to create a customers api. Where should i declare the api? Axios in the action creator session folder? And?

**Comment by rovillesarate** [comment]
Thank you. This is an amazing boilerplate. This makes the development feel like a breeze.

**Comment by huwcarwyn** [comment]
Thank you very much for the kind words :) I uploaded it only as a personal thing but I'm glad others like it too!
