### ISSUE TITLE
CRED not updating values when using select fields

### ISSUE THREAD

**Issue by rovillesarate** [huwcarwyn/react-laravel-boilerplate#30]
Hi Huwcarwyn. I checked out the CRED sample and just wondering if you can provide a sample for select fields. The form can't seem to be able to capture the select fields' value.

i tried using useState and setState hooks but when i submit the form only the input fields value are updated.

```
  const selectTypeProps = (initialValues ? initialValues.select_type : '')
  const [state, setState] = useState({
    select_type: selectTypeProps,
  })

// This updates the selected field value but does not work on submit
  const selectTypeChange = state => {
    const target = state.target
    const name = target.name
    const value = target.value
    console.log(name + ': ' + value) // this works
    setState({
      ...state,
      [name]: value
    })
  }
```
Hope you can help me. Thank you!

**Comment by huwcarwyn** [comment]
Do you mean a select field like a dropdown? And you want that to work with redux forms?

**Comment by huwcarwyn** [comment]
I will add a select field and add an example setting for you

**Comment by huwcarwyn** [comment]
Have a look at this and tell me if it's the kind of thing you were looking for 

https://github.com/huwcarwyn/react-laravel-boilerplate/pull/31
