### ISSUE TITLE
View individual Post on a separate route ( how to setup the individual post selector on react store?)

### ISSUE THREAD

**Issue by rovillesarate** [huwcarwyn/react-laravel-boilerplate#32]
Hi Huwcarwyn. I'm trying to create a separate page for the individual post.

in my app.js
`<Route exact path="/post/:slug" component={PostWithDashboard} />`

How do I create a selector for an individual post?

Action Creator
```
export const GetPost = data => async dispatch => {
  const response = await dispatch(
    makeRequest(`get-post-${data.slug}`, () =>
      axios.put(`/api/posts/${data.slug}`, data)
    )
  )

  dispatch({
    type: actions.GET_POST,
    posts: response.data.data
  })
}
```

Selector
```
export const selectCustomer = state => {
   ???
  return customer
}
```

**Comment by huwcarwyn** [comment]
I will show you an example of some selectors I made in a personal project:

```
import { denormalize } from 'normalizr'
import { createSelector } from 'reselect'

import { selectEntities } from 'store/selectors/entities'
import { entities as entitiesSchema } from 'store/schemas'

const selectGuideSlug = (state, { guideSlug }) => guideSlug

export const selectAllGuides = state => {
  const dnEntities = denormalize(
    { guides: Object.keys(state.entities.guides) },
    entitiesSchema,
    state.entities
  )

  return dnEntities.guides
}

export const selectGuide = createSelector(
  [selectGuideSlug, selectEntities],
  (guideSlug, entities) => {
    const dnEntities = denormalize(
      { guides: [guideSlug] },
      entitiesSchema,
      entities
    )

    return dnEntities.guides[0]
  }
)
```

This should give you enough info to go on IMO

**Comment by rovillesarate** [comment]
Thank you, Huwcarwyn. This will definitely help a lot.

**Comment by rovillesarate** [comment]
Hi Huwcarwyn. How does selectGuideSlug get the slug?
Do I need to set guideSlug on the state using props.match.params.slug
const selectGuideSlug = (state, { guideSlug }) => guideSlug

**Comment by huwcarwyn** [comment]
You will need to pass guideSlug as a prop to the component that is connected. Since that selector is getting guideSlug from ownProps. So for example:

<GuidesList guideSlug="abc123" />
