### ISSUE TITLE
Initial login doesn't run the user data against the UserRepository resulting in a broken avatar link only on login.

### ISSUE THREAD

**Issue by jmarikle** [huwcarwyn/react-laravel-boilerplate#6]
The following line of code just returns `$this->auth->user()->toArray()`, which skips the `UserRepository` being applied to the model.   

https://github.com/huwcarwyn/react-laravel-boilerplate/blob/3eeebe7efcc195b8b35b277090590ca023037630/app/Services/Session/LoginService.php#L48

The result is that this line is never executed

https://github.com/huwcarwyn/react-laravel-boilerplate/blob/3eeebe7efcc195b8b35b277090590ca023037630/app/Transformers/UserTransformer.php#L35

and the avatar url doesn't include the `/storage/` part of the path, making it a broken link.  This only occurs on initial login as far as I can tell, which is probably because that's the only place the user model is returned without using the `userRepo`.

I seem to have fixed this by dependency injecting `App\Contracts\Repository\UserRepositoryContract` into `LoginService.php` and replacing line 48 with `return $this->response->success(['data' => $this->userRepo->currentUser()])->withCookie($apiCookie);` after dependency injecting `userRepo`.

While this works, I have no idea if this is a bad practice or not.  I've never used model repositories before, but I thought I'd at least bring it to your attention and let you know what potential solution I found.

Thanks for the project.  It's really helping me explore the integration of react and laravel.

**Comment by huwcarwyn** [comment]
Good catch! This was a recent change (and a hint to me that I should write more tests)

If you want you could open a PR for the fix? Yours could be PR number 1 😂

**Comment by huwcarwyn** [comment]
I also think that in the case of using the repo, `['data' => $this->userRepo->currentUser()]` can just be replaced with `$this->userRepo->currentUser()` to stop this annoying nesting of 'data' keys (I'm still trying to figure out how to solve this issue in the best way)

**Comment by jmarikle** [comment]
I created a pull request.  I also removed the redundant `data` key and tested it to make sure it didn't break the functionality.  I may be creating another pull request in the future if that's OK.  I noticed that in a few places case sensitivity was causing the javascript to not compile.

**Comment by huwcarwyn** [comment]
Good stuff! Thanks for the PR :D and yea this is very much still a work in progress for me, so if you catch something let me know
